

const API_CONFIG = {
    TRANSLATION_SERVICE_KEY: 'YOUR_GOOGLE_TRANSLATE_API_KEY',
    TRANSLATION_ENDPOINT: 'https://translation.googleapis.com/language/translate/v2',
    UNSPLASH_ACCESS_KEY: 'YOUR_UNSPLASH_ACCESS_KEY',
    WEATHER_API_KEY: 'YOUR_WEATHER_API_KEY'
};

window.API_CONFIG = API_CONFIG;